### ISSUE TITLE
GAMEPLAY-Dialogue system

### ISSUE THREAD

**Issue by PhuongAnh2212** [PhuongAnh2212/Yuri#26]
Phần này còn gì v hachi ơi?

**Comment by natsun08** [comment]
Đã có:
- [x]  Thoại idle random
- [x]  Refences Variable trong thoại
- [x]  Thoại dựa trên condition người nói chuyện
- [x]  Nói chuyện với 1 chara nhiều lần
- [x] Options
- [x] Profile cho Thanh Mai, Angelo, Anh Long và Lam Anh 

Missing:
- [x]  Props signal hỏi về item
- [x]  Props màn hình inventory để giao item
- [x]  Các timeline và state khác nhau liên quan đến quest chính

**Comment by natsun08** [comment]
Kinda done
